#+TITLE: Capacitación Interna - Analisís Vibracional
#+SUBTITLE: 2da Sesión 
#+DATE: 2018/05/24（Jueves）9:00am
#+AUTHOR: Albert Castellano Moreno
#+EMAIL: acastemoreno@gmail.com
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:nil p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+CREATOR: Emacs 25.2.1
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: es
#+SELECT_TAGS: export

#+FAVICON: images/logo-csi.png
#+ICON: images/logo-csi.png

* Medición de Vibración
  :PROPERTIES:
  :SLIDE:    segue dark quote
  :ASIDE:    right bottom
  :ARTICLE:  flexbox vleft auto-fadein
  :END:

** GIGO
Sin buenos datos, no se pueden esperar buenos resultados.[fn:1]
#+BEGIN_CENTER
#+ATTR_HTML: :width 500px
file:images/gigo.jpg
#+END_CENTER
** Buenos resultados
Los pasos para obtener buenos resultados son:
- Asegurarse que estamos usando el sensor adecuado, montado correctamente.
- Asegurarse que siempre se realizan las medidas de la misma forma. =Repetitividad=
** Requerimientos del Sensor
El primer paso para seleccionar el sensor es elegir *que necesitamos medir* (Desplazamiento, Velocidad, Aceleración). Para este paso se tienen en consideración la *velocidad de la máquina*.

Lo siguiente que tenemos que definir es el *modelo adecuado con el entorno de medida*. Consideraremos la temperatura de medida, el espacio de instalación, presencia de agua u otros liquidos, etc.

Finalmente se elige la *técnica y ubicacion de montaje*. Esta elección estara determinada por el tipo de máquina, naturaleza de la superficie de máquina y otros factores del entorno, el *rango de frecuencia requerido*, y demas consideraciones de accesibilidad.

** Repetitividad
Cada vez que se mide una máquina se debe hacer de la misma manera. Ademas la máquina debe operar en las mismas condiciones en cada medición (*Carga y Velocidad*)
#+BEGIN_CENTER
#+ATTR_HTML: :width 450px
file:images/foto_medicion.jpg
#+END_CENTER
** Vida util y desgaste del sensor
Una vez se lleva algún tiempo recogiendo datos, y sabes que el metodo de medición es repetible, se espera que los sensores se descalibren y que fallen. EL sensor mostrara signos de desgaste y falla en la señal medida. Más adelante veremos como reconocer estos fallos.

Se recomienda calibrar o reemplazar los sensores anualmente.
* Aceleración, velocidad o desplazamiento?
  :PROPERTIES:
  :SLIDE:    segue dark quote
  :ASIDE:    right bottom
  :ARTICLE:  flexbox vleft auto-fadein
  :END:

** 
  :PROPERTIES:
  :FILL:     images/vibration_severity.jpg
  :TITLE:    white
  :SLIDE:    white background-center
  :END:

* Tipos de transductores
  :PROPERTIES:
  :SLIDE:    segue dark quote
  :ASIDE:    right bottom
  :ARTICLE:  flexbox vleft auto-fadein
  :END:
** Sensores de desplazamiento
Son usados típicamente en *monitorizado en continuo*. El sensor no va en el exterior de la máquina. Esta montado en un apoyo con *vision directa al eje* (requiere un agujero pasante). Son llamados sondas de proximidad o sondas Eddy Current (corriente de foucault)
#+BEGIN_CENTER
#+ATTR_HTML: :width 330px
file:images/sonda_de_proximidad.jpg
#+END_CENTER
** Sensores de desplazamiento
En la mayoria de casos se instalan pares formando un angulo de 90°. Esto permite generar un =diagrama de órbitas= (movimiento del eje en el apoyo). 
#+BEGIN_CENTER
#+ATTR_HTML: :width 370px
file:images/orbit_example.png
#+END_CENTER
** Sensores de desplazamiento
_Ventajas_:
- Respuesta de baja frecuencia (hasta 5 Hz).
- Mide el desplazamiento relativo entre el eje y el apoyo.
- Son fiables, si han sido bien montados.

_Desventajas_:
- Son caros y dificiles de instalar.
- No se pueden usar para medidas de alta frecuencia.
- Su calibración (se determina con el cociente entre el voltaje de salida y el desplazamiento real) depende del material del eje.
- El desgaste del eje y los defectos en su superficie producen señales falsas.
** Sensores de Velocidad
Aun cuando *es frecuente usar amplitudes en unidades de velocidad*, los *sensores de velocidad no se usan* frecuentemente.
El sensor de velocidad es básicamente un imán suspendido, montado entre un muelle y un amortiguador.
#+BEGIN_CENTER
#+ATTR_HTML: :width 370px
file:images/sensor_de_velocidad.jpg
#+END_CENTER
** Sensores de Velocidad
_Ventajas_:
- No necesita energía del exterior, el propio sistema genera electricidad.
- La señal de salida es potente.

_Desventajas_:
- No es adecuado para medidas de baja y alta frecuencia.
- Hay cambios en la sensibilidad con la temperatura.
- Debido a las partes internas móviles. el desgaste puede acortar su tiempo de vida.
- Los sensores son bastante grandes.
** Acelerometros   
Los acelerómetros son los *sensores más utilizados* en análisis vibracional. El más comun es el piezoeléctrico con un amplificador interno. Un material piezoelectrico (cristal) se *comprime y descomprime* dentro del sensor produciendo un *carga* la cual es *amplificada* mediante una *corriente constante*.
#+BEGIN_CENTER
#+ATTR_HTML: :width 220px
file:images/sensor_de_aceleracion.jpg
#+END_CENTER
** Acelerometros
Cuando un acelerómetro se conecta a la fuente de vibración, el amplificador necesita unos pocos segundos para estabilizarse.

Si la espera es demasiado corta, en el espectro se mostrará una rampa descendente conocida como "ski-slope".
#+BEGIN_CENTER
#+ATTR_HTML: :widt5 500px
file:images/ski-slope.jpg
#+END_CENTER
** Acelerometros Triaxiales
Un acelerometros triaxiales consisten en 3 acelerometros montados ortogonalmente entre ellos, montados en un unico bloque.
#+BEGIN_CENTER
#+ATTR_HTML: :width 400px
file:images/triaxial.jpg
#+END_CENTER
** Sensibilidad de acelerometro
Mediante un proceso llamado *integracion* se puede medir *desplazamiento y velocidad* desde un acelerometro. *Pero no todo acelerometro funciona para esta labor*.

Para elegir el *acelerometro adecuado* se debe tener en cuenta la *sensibilidad del acelerometro*. La *sensibilidad* es una medida de los *niveles de tension* que obtienes en en respuesta *a un nivel fijo de vibracion*.

La sensibilidad se expresa en =mV/g=
** 
Alta sensibilidad (500 mV/g a 1V/g):
- Maquina de precision.
- Baja velocidad.
- Bajo nivel de vibracion.

Baja sensibilidad (menor a 50 mV/g):
- Maquinas grandes.
- Altas velocidades.
- Alto nivel de vibracion.

Mediana sensibilidad (~100mV/g)
- De proposito general.

** 
  :PROPERTIES:
  :FILL:     images/sensibilidades.jpg
  :TITLE:    white
  :SLIDE:    white background-center
  :END:

** Acelerometros
_Ventajas_:
- Amplio rango de frecuencias.
- Pueden ser usados para analizar rodamientos (alta frecuencia).
- Pueden medir velocidad mediante un proceso llamado integración (igualmente con el desplazamiento mediante doble integración)
  
_Desventajas_:
- Limitaciones en la temperatura debido al amplificador interno.
** 
  :PROPERTIES:
  :FILL:     images/requerimientos_sensores.jpg
  :TITLE:    white
  :SLIDE:    white background-center
  :END:

* Entorno de medida
  :PROPERTIES:
  :SLIDE:    segue dark quote
  :ASIDE:    right bottom
  :ARTICLE:  flexbox vleft auto-fadein
  :END:

** Entorno de medicion
Si bien los sensores son diseñados para ser robustos, tienen un limite a la temperatura debido a su amplificador interno.

Por encima de 150°C (300°F), se recomienda usar transductores en modo de carga.

#+BEGIN_CENTER
#+ATTR_HTML: :width 350px
file:images/ambiente_con_alta_temperatura.jpg
#+END_CENTER

* Montaje del sensor
  :PROPERTIES:
  :SLIDE:    segue dark quote
  :ASIDE:    right bottom
  :ARTICLE:  flexbox vleft auto-fadein
  :END:

** 
  :PROPERTIES:
  :FILL:     images/tipos_de_montaje.jpg
  :TITLE:    white
  :SLIDE:    white background-center
  :END:
** Cuantos sensores instalar
Se recomientas instalar:
- 2 sensores radiales en cada apoyo (puede ser  vertical y horizontal)
- 1 sensor axial por eje

** Donde NO instalar el transductor
- En lugares donde exista poca superficie de contacto.
- En la cubierta de los ventiladores.
- Entre las aletas de enfriamiento del estator, a menos que exista suficiente espacio para albergar el sensor y suficiente superficie de contacto.
- En lugares donde exista una mala preparacion de superficie.

** Preparacion de superficie
#+BEGIN_CENTER
#+ATTR_HTML: :width 900px
file:images/spot_face.jpg
#+END_CENTER
#+BEGIN_CENTER
Spot face tool
#+END_CENTER

** 
  :PROPERTIES:
  :FILL:     images/mal_montaje1.jpg
  :TITLE:    white
  :SLIDE:    white background-center
  :END:

** 
  :PROPERTIES:
  :FILL:     images/mal_montaje2.jpg
  :TITLE:    white
  :SLIDE:    white background-center
  :END:

** 
  :PROPERTIES:
  :FILL:     images/buen_montaje.jpg
  :TITLE:    white
  :SLIDE:    white background-center
  :END:

* Thank You ˊ・ω・ˋ
:PROPERTIES:
:SLIDE: thank-you-slide segue
:ASIDE: right
:ARTICLE: flexbox vleft auto-fadein
:END:
* Footnotes

[fn:1] Garbage In, Garbage Out
